---
# This playbook fixes PSReadLine module and disables POWERSHELL_TELEMETRY
- name: Fix  PSReadLine module and disable POWERSHELL_TELEMETRY
  win_shell: |
    Set-ExecutionPolicy RemoteSigned -Force
    Remove-Module PSReadLine
    Remove-Item 'C:\Program Files\WindowsPowerShell\Modules\PSReadLine' -Force -Recurse
    Install-Module -Name PSReadLine -RequiredVersion 2.2.0-beta3 -Scope AllUsers -Force
  become: yes
  become_method: runas
  become_user: System
  ignore_errors: true
    
- name: Disable POWERSHELL_TELEMETRY
  raw: setx /M POWERSHELL_TELEMETRY_OPTOUT 1
