---
# This playbook installs OpenSSH with SaltMinion (problem desription is https://www.reddit.com/r/PowerShell/comments/bjxzf2/addwindowscapability_on_a_remote_computer/)
- name: Install SaltMinion
  win_chocolatey:
    name: saltminion
    state: present

- name: Install OpenSSH (server and client)
  win_shell: |
    cd C:\salt
    .\salt-call.bat --local cmd.powershell "Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0"
    .\salt-call.bat --local cmd.powershell "Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0"
    Start-Sleep -s 90
    Set-Service sshd -StartupType Automatic
    Set-Service ssh-agent -StartupType Automatic
    Start-Service sshd
    Start-Service ssh-agent
    New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
  become: yes
  become_method: runas
  become_user: System
  ignore_errors: true

- name: Uninstall SaltMinion
  win_chocolatey:
    name: saltminion
    state: absent

- name: Clean temp files
  win_shell: |
    Remove-Item "C:\salt" -Force -Recurse -ErrorAction SilentlyContinue 
    Remove-Item "C:\*.msu" -Force -Recurse -ErrorAction SilentlyContinue
