---
# This playbook removes WordPad and MSPaint
- name: Remove WordPad and MSPaint
  win_shell: |
    Remove-WindowsCapability -Online -Name Microsoft.Windows.WordPad~~~~0.0.1.0
    Remove-WindowsCapability -Online -Name Microsoft.Windows.MSPaint~~~~0.0.1.0
  become: yes
  become_method: runas
  become_user: System
  ignore_errors: true
